<footer>
    <p class="friend-link">友情链接：<a href="https://data.fitvdna.com">FITV电影电视剧数据库</a></p>
    <div class="copy-right">
        <p><span>Copyright © 2002-2018 www.beimen.com All Rights Reserved</span>版权所有 涿州北门文化传媒有限公司</p>
        <p>涿州北门文化传媒有限公司 备案号 沪ICP备08017520号-1</p>
        <p>请所有作者发布作品时务必遵守国家互联网信息管理办法规定，我们拒绝任何色情剧本，一经发现，即作删除！</p>
        <p>本站所收录的作品、社区话题、用户评论、用户上传内容或图片等均属用户个人行为。如前述内容侵害您的权益，欢迎举报投诉，一经核实，立即删除，本站不承担任何责任</p>
        <p>联系方式 总机 ??? 地址：???</p>
    </div>
</footer> 